// <auto-generated />
using KanbanBoard.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace KanbanBoard.Migrations
{
    [DbContext(typeof(DashboardContext))]
    [Migration("20180204222047_update")]
    partial class update
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KanbanBoard.Models.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int>("StatePriority");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("StatePriority");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("KanbanBoard.Models.State", b =>
                {
                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Priority");

                    b.ToTable("States");
                });

            modelBuilder.Entity("KanbanBoard.Models.Card", b =>
                {
                    b.HasOne("KanbanBoard.Models.State", "State")
                        .WithMany()
                        .HasForeignKey("StatePriority")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
